### ISSUE TITLE
install dependencies error

### ISSUE THREAD

**Issue by huminted** [whotto/Video_note_generator#2]
pip3 install --no-cache-dir -r requirements.txt

Collecting openai>=1.0.0 (from -r requirements.txt (line 1))
  Downloading openai-1.57.4-py3-none-any.whl.metadata (24 kB)
Collecting httpx>=0.24.1 (from -r requirements.txt (line 2))
  Downloading httpx-0.28.1-py3-none-any.whl.metadata (7.1 kB)
Collecting yt-dlp>=2023.11.16 (from -r requirements.txt (line 3))
  Downloading yt_dlp-2024.12.13-py3-none-any.whl.metadata (172 kB)
Collecting openai-whisper>=2023.11.17 (from -r requirements.txt (line 4))
  Downloading openai-whisper-20240930.tar.gz (800 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 800.5/800.5 kB 21.0 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [25 lines of output]
      <string>:5: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
      Traceback (most recent call last):
        File "/Users/humin/Project/Video_note_generator/path/to/venv/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
          ~~~~^^
        File "/Users/humin/Project/Video_note_generator/path/to/venv/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ~~~~^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/humin/Project/Video_note_generator/path/to/venv/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/private/var/folders/_c/pxpk9t8x7wsdt4_0lclb65lh0000gn/T/pip-build-env-8so17f_k/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 334, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/_c/pxpk9t8x7wsdt4_0lclb65lh0000gn/T/pip-build-env-8so17f_k/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 304, in _get_build_requires
          self.run_setup()
          ~~~~~~~~~~~~~~^^
        File "/private/var/folders/_c/pxpk9t8x7wsdt4_0lclb65lh0000gn/T/pip-build-env-8so17f_k/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 522, in run_setup
          super().run_setup(setup_script=setup_script)
          ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/_c/pxpk9t8x7wsdt4_0lclb65lh0000gn/T/pip-build-env-8so17f_k/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 320, in run_setup
          exec(code, locals())
          ~~~~^^^^^^^^^^^^^^^^
        File "<string>", line 21, in <module>
        File "<string>", line 11, in read_version
      KeyError: '__version__'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

**Comment by lycos123456** [comment]
python版本太高了，我换成3.10解决了
